name: "TODOs to Issues"
on: [push, pull_request]

jobs:
  todo_issues:
    runs-on: ubuntu-latest
    name: A job to create issues from todos
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get todos action step
        id: issue
        uses: LarvenLLC/todo-issues@v1
